---
#Handler example
- hosts: remote
  become: yes
  become_user: root
  vars:
   - docroot: /var/www/test.com/public
  tasks:
  - name: Install Nginx
    apt:
     name: nginx
     state: installed
     update_cache: true
    notify:
     - Start Nginx

  - name: Create Web Root 
    file:
     path: '{{ docroot }}'
     mode: 775
     state: directory
     owner: www-data
     group: www-data
    notify:
     - Reload Nginx

  handlers:
   - name: Start Nginx
     service:
      name: nginx
      state: started

   - name: Reload Nginx
     service:
      name: nginx
      state: reloaded 
